### ISSUE TITLE
Can't evaluate activities

### ISSUE THREAD

**Issue by colabcolibri** [bdecentgmbh/moodle-tool_skills#1]
I saw in the description of the plugin that it can also be used to evaluate the activities, not just the course. But I tested, tested and tested, and didn't found a way to evaluate the activities individually.

I'm using moodle 4.3

**Comment by stefanscholz** [comment]
Hi @colabcolibri,

this plugin will — like most of our plugins — have a free and a pro version. And the feature you are looking for is only available in the pro version, which is not publicly available.

In short:

- Free will allow you to manage skills and add skills to courses.
- Pro will allow you add skills also to activities, and you'll get a report source to monitor it. 

We will also introduce 3 widgets in our Dash Pro plugin which let you display the skill progress, levels and important KPIs on your dashboard (or somewhere else).

We will publish the products on our website shortly, and then there will be a feature comparison for the free and the pro plugin.

You will be able to test all features on our main demo site (bdecent.io) next week. In the meantime, feel free to create a user account on https://m41.bdecent.io/ and check it out there. (every new user gets his own test course with editing rights there)

Hope this helps!
Stefan

**Comment by colabcolibri** [comment]
I'm willing to be a pro user. 😬

I will comment in the other post about my use case, that you asked.
