### ISSUE TITLE
Unused element: Image in level

### ISSUE THREAD

**Issue by safatshahin** [bdecentgmbh/moodle-tool_skills#10]
Can't see any use of the image for the level anywhere, is that created as a part of a future release?
If so, it should live in a different branch and added when it has a use.

**Comment by stefanscholz** [comment]
Similar to the color, the image is used in a widget that displays the user's skill progression, which is going to be released a bit later. To avoid confusion, we've removed it for now, and will bring it back later, as per your recommendation.

![Bildschirmfoto 2024-04-18 um 14 45 38](https://github.com/bdecentgmbh/moodle-tool_skills/assets/3414705/93969915-d3be-4f96-b027-2d7ddf9a9cda)
