### ISSUE TITLE
Issues with observer oriented architecture

### ISSUE THREAD

**Issue by safatshahin** [bdecentgmbh/moodle-tool_skills#11]
Currently, skill assignments are observer oriented. This means, that if a user gets points/skills, they are static and won't be updated when the course setup for skills is updated.
There should be either a scheduled task/another observer to listed to course skill setup updated and update user skills accordingly with the changes in the course setup.

**Comment by stefanscholz** [comment]
We have improved the skills points earning architecture to update users' points immediately when the course setup has been changed.
