### ISSUE TITLE
Moving to hooks from observers

### ISSUE THREAD

**Issue by safatshahin** [bdecentgmbh/moodle-tool_skills#12]
Moodle 4.3 introduced hooks api which is the replacement of the events API:
https://moodledev.io/docs/4.3/apis/core/hooks

It is recommended to use hooks API going forward which is far more efficient and aligned with psr framework.

**Comment by stefanscholz** [comment]
Thank you for your recommendation, that certainly makes sense.
We are considering moving to hooks in a future release for 4.3 upwards.
I've added this to our internal backlog (SKI-162).
