### ISSUE TITLE
Invalid string identifer error while installing the plugin

### ISSUE THREAD

**Issue by safatshahin** [bdecentgmbh/moodle-tool_skills#4]
Invalid get_string() identifier: 'subplugintype_skilladdon_plural' or component 'tool_skills'. Perhaps you are missing $string['subplugintype_skilladdon_plural'] = ''; in /var/www/moodle/master_402/moodle/admin/tool/skills/lang/en/tool_skills.php?

    line 355 of /lib/classes/string_manager_standard.php: call to debugging()
    line 6992 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
    line 621 of /lib/classes/plugin_manager.php: call to get_string()
    line 1063 of /admin/renderer.php: call to core_plugin_manager->plugintype_name_plural()
    line 206 of /admin/renderer.php: call to core_admin_renderer->plugins_check_table()
    line 707 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()

**Comment by stefanscholz** [comment]
We have added the "subplugintype_skilladdon_plural" string to the tool_skills language file:
https://github.com/bdecentgmbh/moodle-tool_skills/blob/dev/lang/en/tool_skills.php#L38
