### ISSUE TITLE
Error in assign skills page in course

### ISSUE THREAD

**Issue by safatshahin** [bdecentgmbh/moodle-tool_skills#6]
The following options are not valid: overflow

    line 1377 of /lib/weblib.php: call to debugging()
    line 132 of /admin/tool/skills/classes/table/course_skills_table.php: call to format_text()
    line 861 of /lib/tablelib.php: call to tool_skills\table\course_skills_table->col_description()
    line 2084 of /lib/tablelib.php: call to flexible_table->format_row()
    line 2208 of /lib/tablelib.php: call to table_sql->build_table()
    line 127 of /admin/tool/skills/manage/courselist.php: call to table_sql->out()

**Comment by stefanscholz** [comment]
We have resolved the overflow issue on the "Manage skills" page.
