### ISSUE TITLE
Fault: Set level for course 

### ISSUE THREAD

**Issue by safatshahin** [bdecentgmbh/moodle-tool_skills#8]
Upon course completion, if the level for the course is set to a specific level, it should assign the points for that level to the user.
But it's not assigning any points.

**Comment by stefanscholz** [comment]
Hi @safatshahin,

we have reviewed this issue, and it seems to be working as expected. 

Here are the steps we tested:
1. Created a skill named "New skill" with level one named "Intermediate" requiring 10 points, and level two named "Expert" requiring 20 points.
2. Set up a course with two pages and configured course completion to depend on the completion of the two pages.
3. Enabled the skill and set it to be updated upon course completion to "Set level" to "Intermediate".
4. Enrolled a student in the course and completed the two pages to complete the course.
5. Upon completion, the student's skill level was appropriately updated to Intermediate and the student has the earned 10 points (which matches the skill level).

Please re-test with the latest version of the plugin and re-open this issue with reproduction steps if you can still reproduce the issue.

Many thanks!
Stefan
