### ISSUE TITLE
Unused element: Color in level and skill

### ISSUE THREAD

**Issue by safatshahin** [bdecentgmbh/moodle-tool_skills#9]
What is the actual use of color in the skill and the level?
Can't see any usage anywhere, whats the point of having that in the setup?

**Comment by stefanscholz** [comment]
The color is used in a widget that display's the user's skill progression, which is going to be released a bit later.
To avoid confusion, we've removed it for now, and will bring it back later.

![Bildschirmfoto 2024-04-18 um 14 45 38](https://github.com/bdecentgmbh/moodle-tool_skills/assets/3414705/93969915-d3be-4f96-b027-2d7ddf9a9cda)
